import java.io.IOException;

import AFINN.AFINN;
import SWN.SentiWordNet;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        try {
            AFINN afinn = new AFINN("res/AFINN-111.txt");
            System.out.println("AFINN SCORE: " + afinn.score(args[0]));

            SentiWordNet swn = new SentiWordNet("res/swn.txt");
            System.out.println("SWN SCORE: " + swn.score(args[0]));

        } catch (IOException e) {
			e.printStackTrace();
		}

    }

}
